# Generated by Django 3.2.16 on 2022-10-15 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Master',
            fields=[
                ('Dept_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Dept_Name', models.TextField()),
                ('Dept_description', models.TextField()),
                ('Dept_Status', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation_Master',
            fields=[
                ('Desg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Desg_Name', models.TextField()),
                ('Desg_description', models.TextField()),
                ('Desg_Is_Active', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Master',
            fields=[
                ('Emp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email_ID', models.TextField()),
                ('First_Name', models.TextField()),
                ('Middle_Name', models.TextField(blank=True)),
                ('Last_Name', models.TextField()),
                ('Contact_Number', models.IntegerField(blank=True)),
                ('Joining_Date', models.DateTimeField(blank=True)),
                ('Job_Role', models.CharField(blank=True, max_length=10)),
                ('Emp_Sex', models.TextField(blank=True)),
                ('Birth_Date', models.DateField(blank=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Dept_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.dept_master')),
                ('Desg_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.designation_master')),
            ],
        ),
    ]
