# Generated by Django 3.2.16 on 2022-11-27 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Type',
            fields=[
                ('Attendance_Type_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Attendance_Type_Name', models.CharField(max_length=100)),
                ('Attendance_Type_Code', models.CharField(max_length=5)),
                ('Attendance_Type_Description', models.CharField(max_length=200)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_Master',
            fields=[
                ('Dept_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Dept_Name', models.CharField(max_length=100, unique=True)),
                ('Dept_description', models.TextField(blank=True, null=True)),
                ('Dept_Status', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation_Master',
            fields=[
                ('Desg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Desg_Name', models.CharField(blank=True, max_length=100, unique=True)),
                ('Desg_description', models.TextField(blank=True, null=True)),
                ('Desg_Status', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Dept_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.dept_master')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Master',
            fields=[
                ('Emp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email_ID', models.CharField(blank=True, max_length=200, unique=True)),
                ('First_Name', models.CharField(blank=True, max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100)),
                ('Last_Name', models.CharField(blank=True, max_length=100)),
                ('Contact_Number', models.CharField(blank=True, max_length=10)),
                ('Joining_Date', models.DateField(blank=True)),
                ('Project_Id', models.IntegerField(blank=True, null=True)),
                ('Emp_Sex', models.CharField(blank=True, max_length=100)),
                ('Birth_Date', models.DateField(blank=True)),
                ('Emp_Status', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Dept_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.dept_master')),
                ('Desg_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.designation_master')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Master',
            fields=[
                ('Proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('Proj_Name', models.CharField(blank=True, max_length=100, unique=True)),
                ('Proj_Description', models.TextField(blank=True, null=True)),
                ('Client_Name', models.CharField(blank=True, max_length=100)),
                ('Point_of_Contact_Name', models.CharField(blank=True, max_length=100)),
                ('Point_of_Contact_Email', models.CharField(blank=True, max_length=100, unique=True)),
                ('Proj_Start_Date', models.DateField(blank=True)),
                ('Proj_End_Date', models.DateField(blank=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Master',
            fields=[
                ('Role_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(blank=True, max_length=100, unique=True)),
                ('Role_description', models.TextField(blank=True, null=True)),
                ('Role_Status', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Master',
            fields=[
                ('Shift_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Shift_Name', models.CharField(max_length=100, unique=True)),
                ('Shift_Start_Time', models.TimeField()),
                ('Shift_End_Time', models.TimeField()),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Shift_Master',
            fields=[
                ('Emp_Shift_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Shift_Start_Time', models.TimeField()),
                ('Shift_End_Time', models.TimeField()),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.emp_master')),
                ('Shift_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.shift_master')),
            ],
        ),
        migrations.AddField(
            model_name='emp_master',
            name='Role_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.role_master'),
        ),
        migrations.CreateModel(
            name='Attendance_Master',
            fields=[
                ('Attendance_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Attendance_Date', models.DateField()),
                ('Clock_In_Time', models.TimeField(blank=True, null=True)),
                ('Clock_Out_Time', models.TimeField(blank=True, null=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Attendance_Type_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.attendance_type')),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.emp_master')),
                ('Emp_Shift_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.employee_shift_master')),
            ],
        ),
    ]
