# Generated by Django 3.2.16 on 2022-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation_master',
            name='Desg_Name',
            field=models.TextField(unique=True),
        ),
    ]
