# Generated by Django 3.2.16 on 2022-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='Project_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
