# Generated by Django 3.2.16 on 2022-11-11 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0002_alter_emp_master_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Master',
            fields=[
                ('Attendance_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Attendance_Date', models.DateField()),
                ('Clock_In_Time', models.TimeField()),
                ('Clock_Out_Time', models.TimeField()),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.emp_master')),
            ],
        ),
    ]
