# Generated by Django 3.2.16 on 2022-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0002_alter_designation_master_desg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_master',
            name='Dept_Name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='Email_ID',
            field=models.TextField(unique=True),
        ),
    ]
