# Generated by Django 3.2.16 on 2022-10-24 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0003_auto_20221024_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Master',
            fields=[
                ('Role_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.TextField(unique=True)),
                ('Role_description', models.TextField()),
                ('Role_Is_Active', models.BooleanField(default=True)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='Job_Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_App.role_master'),
        ),
    ]
