# Generated by Django 3.2.16 on 2022-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0003_attendance_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_master',
            name='Clock_In_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_master',
            name='Clock_Out_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
