# Generated by Django 3.2.16 on 2022-10-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0004_auto_20221024_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation_master',
            old_name='Desg_Is_Active',
            new_name='Desg_Status',
        ),
        migrations.RenameField(
            model_name='emp_master',
            old_name='Is_Active',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='role_master',
            old_name='Role_Is_Active',
            new_name='Role_Status',
        ),
    ]
