# Generated by Django 3.2.16 on 2022-11-13 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0004_auto_20221112_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Type',
            fields=[
                ('Attendance_Type_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Attendance_Type_Name', models.CharField(max_length=100)),
                ('Attendance_Type_Code', models.CharField(max_length=5)),
                ('Attendance_Type_Description', models.CharField(max_length=200)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Modified_By', models.IntegerField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance_master',
            name='Attendance_Type_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee_App.attendance_type'),
        ),
    ]
