# Generated by Django 3.2.16 on 2022-10-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0005_auto_20221024_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_master',
            old_name='Status',
            new_name='Emp_Status',
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='Joining_Date',
            field=models.DateField(blank=True),
        ),
    ]
