# Generated by Django 3.2.16 on 2022-10-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_App', '0006_auto_20221028_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_master',
            old_name='Job_Role',
            new_name='Role_Id',
        ),
    ]
